# coding: utf-8
# OceanBase Deploy.
# Copyright (C) 2021 OceanBase
#
# This file is part of OceanBase Deploy.
#
# OceanBase Deploy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# OceanBase Deploy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OceanBase Deploy.  If not, see <https://www.gnu.org/licenses/>.
### use to filter cases
### regression name: c,cp,j,jp,o,op,slave,proxy

#partition_range_test=["partition.ob_partition_hash_range", "partition.ndb_partition_range","partition.ob_partition_range", "partition.ob_partition_range_expr", "partition.ob_partition_trx", "partition.ob_partition_consistency", "partition.tc_partition_change_from_range_to_hash_key", "partition.partition_max_parts_range_innodb", "partition.ob_partition_hash_range", "partition.ob_partition_ddl", "partition.partition_max_sub_parts_range_innodb"]
partition_range_test=["partition.ob_partition_consistency", "partition.ob_partition_ddl", "partition.ob_partition_hash_range", "partition.partition_max_parts_range_innodb", "partition.ob_partition_range_expr", "partition.partition_max_sub_parts_range_innodb",
 "partition.tc_partition_change_from_range_to_hash_key", "partition.ob_partition_trx"]

#ps_test=[]
ps_test=["ps.index_28_trx_concu_multi_dml_ps","ps.jdbc_ps_insert","ps.ps_affect_rows","ps.ps_datatype","ps.ps_lose_replace","ps.ps_max_concurrent","ps.sfu_norow_ps","ps.index_29_trx_concu_compound_ps","ps.jdbc_replace_ps","ps.ps_basic","ps.ps_execute_repeat","ps.ps_lose_replace_tr","ps.ps_muticonn_execute_repeat","ps.sql_audit_c_ps","ps.index_31_unique_ps","ps.jdbc_replace_ps_trx","ps.ps_cache","ps.ps_lose_cur_time","ps.ps_lose_select","ps.ps_muticonn_stress","ps.trx_expire_index_ps_1","ps.bigvarchar_ps","ps.index_45_ps_expire_1","ps.join_ps_bug","ps.ps_complex","ps.ps_lose_delete","ps.ps_lose_select_tr","ps.ps_normal","ps.trx_expire_index_ps_2","ps.decode_ps","ps.index_45_ps_expire_2","ps.ps_1","ps.ps_complex_delete","ps.ps_lose_delete_tr","ps.ps_lose_update","ps.ps_order_by","ps.update_delete_limit_ps","ps.decode_ps_return_type","ps.index_46_drop_ps","ps.ps_2","ps.ps_complex_insert","ps.ps_lose_insert","ps.ps_lose_update_tr","ps.ps_outline","ps.decode_ps_tbl","ps.jdbc_ps_all_statement","ps.ps_3","ps.ps_complex_replace","ps.ps_lose_insert_tr","ps.ps_lose_when","ps.ps_stress","ps.index_26_trx_concu_dml_samerow_ps","ps.jdbc_ps_complex","ps.ps_abs","ps.ps_complex_update","ps.ps_lose_muticonn","ps.ps_lose_when2","ps.ps_varchar"]

obsolete_px_function_list=['multi_partition_pq']

spm=['spm.spm_expr','spm.spm_with_acs_new_plan_not_ok']

merge_into=['merge_into.merge_insert','merge_into.merge_into_normal', 'merge_into.merge_subquery', 'merge_into.merge_update']

# Temporary failure, remove this after updatable view commit.
updatable_view = ['view.is_views', 'create_frommysql' ]

excludes=['pl.sp-error-big_mysql','bug217660_xiaochu', 'collect','trx_collect', 'tenant.resource_pool_new',
          'ps_cache',"parawhen_manytimes_outwaitlock","parawhen_manytimes_waitlock","ps_lose_when2","ps_lose_when","update_rowkey_when","when1","when2","when3","when_clause","when_idx_range","when_idxs_range","when_nest1","when_nonrowkey_range","when_nonrowkey_range_withidx","when_parallel1","when_parallel2","when_parallel3","when_select_for_update_wait","when_trx2","jdbc_ps_complex","ps_complex_delete","ps_complex_insert","ps_complex_replace","ps_complex","ps_complex_update","trx_complex","expire_bug5328455","expire_index","expire_index_trxdel","expire","expire_trx2","expire_trx_drop_tbl","expire_trx_modifydata","expire_trx_nop","expire_trx_replace2","expire_trx_replace","expire_trx","expire_trx_update","expire_unique_index_trxdel","index_45_ps_expire_1","index_45_ps_expire_2","trx_expire_alter_drop_add_col_idx","trx_expire_alter_drop_add_col","trx_expire_idx_unique_merge_step","trx_expire_index_ps_1","trx_expire_index_ps_2","trx_expire_more_oper","trx_expire_step_merge_num","zaddlmajor_gt64times_expire_trx","decode_col_convert","decode_extra_jdbc","aproject_account","decode_ps_return_type","decode_ps_tbl","decode_ps","decode_return_type","func_decode","bigvarchar_prejoin","prejoin_tabletype","prejoin","prejoin_update_basic","compound_bug","idx_unique_compound","index_29_trx_concu_compound_ps","ups_quick_compound_partital_rollback1","ups_quick_compound_partital_rollback","update_delete_compund","update_delete_compund_idx","update_delete_compund_uni","outline.outline_no_hint_check_hit","inner_table.all_virtual_sql_plan_monitor", "plan_cache.plan_cache_late_compile", "plan_cache.plan_cache_retry", "ocp", "update.update_ignore_multi_row", "update.update_ignore_multi_stmt", "update.update_ignore_one_row", "materialized_view.mv_basic3", "like_goes_index_dilang", "test_wisconsin","jit.expr_jit_basic_mysql"] + partition_range_test + obsolete_px_function_list + spm + merge_into + updatable_view

c_list=['ps_affect_rows',
        'affect_rows',
        'master_ups_lost_causedby_switch_twice',
        'deadlock_causedby_ups_switch',
	'information_schema.information_schema_db_nt',
        'jdbc_ps_complex',
        'jdbc_trx_with_merge',
        'jdbc_parallel_trx',
        'jdbc_ps_insert',
        'jdbc_ps_all_statement',
	'jdbc_replace_ps',
	'jdbc_replace_ps_trx',
	'jdbc_replace_parallel_trx',
        'hex_ip_java',
        'decode_ps_return_type',
        'decode_return_type',
        'decode_ps_return_type',
        'decode_return_type',
        'ps_lose_delete','ps_lose_delete_tr','ps_lose_insert','ps_lose_insert_tr','ps_lose_muticonn','ps_lose_replace','ps_lose_replace_tr','ps_lose_select','ps_lose_select_tr','ps_lose_update','ps_lose_update_tr','ps_muticonn_stress','ps_lose_when','ps_lose_when2',
        'bind_variable_stress_greater_then_65535','bind_variable_stress_65535','update_rowkey_basic','update_rowkey_bug5003370','decode_extra_jdbc','func_sign','sql_audit_c_ps',"bigvarchar_ps","deadlock_causedby_ups_switch","decode_ps_return_type","decode_ps_tbl","decode_ps","index_26_trx_concu_dml_samerow_ps","index_28_trx_concu_multi_dml_ps","index_29_trx_concu_compound_ps","index_31_unique_ps","index_45_ps_expire_1","index_45_ps_expire_2","index_46_drop_ps","jdbc_ps_all_statement","jdbc_ps_complex","jdbc_ps_insert","jdbc_replace_ps","jdbc_replace_ps_trx","join_ps_bug","master_ups_lost_causedby_switch_twice","ps_1","ps_2","ps_3","ps_affect_rows","ps_basic","ps_cache","ps_complex_delete","ps_complex_insert","ps_complex_replace","ps_complex","ps_complex_update","ps_execute_repeat","ps_lose_cur_time","ps_lose_delete","ps_lose_delete_tr","ps_lose_insert","ps_lose_insert_tr","ps_lose_muticonn","ps_lose_replace","ps_lose_replace_tr","ps_lose_select","ps_lose_select_tr","ps_lose_update","ps_lose_update_tr","ps_lose_when2","ps_lose_when","ps_muticonn_execute_repeat","ps_muticonn_stress","ps_order_by","ps_stress","ps_varchar","sfu_norow_ps","sql_audit_c_ps","trx_expire_index_ps_1","trx_expire_index_ps_2","update_delete_limit_ps","upsmutiget","ups_quick_compound_partital_rollback1","ups_quick_compound_partital_rollback","vector_nps","bug_prepare_core","index_30_trx_prepare_in_trx","join.nested_loop_join_prepare_joinon","join.nested_loop_join_prepare_joinon_where","join.nested_loop_join_prepare","func_group_3","func_like_index","idx_const_basic_one","idx_const_basic_one_time","idx_const_basic_one_varchar","idx_unique_dml_varchar","idx_unique_many_idx","limitnegative","join.nested_loop_join","join.nested_loop_join_idx","join.nested_loop_join_idx_joinon","join.nested_loop_join_idx_joinon_where","join.nested_loop_join_idx_usenl","join.nested_loop_join_idx_usenl_joinon","join.nested_loop_join_idx_usenl_joinon_where","join.nested_loop_join_joinon","join.nested_loop_join_joinon_where","nop","nop_index","nop_index_default","nop_index_multi_rowkey","nop_multi_rowkey","update_delete_orderby_limit","update_delete_orderby_limit_idx","update_delete_orderby_limit_unique","update_hot","type_date.update_timestamp_affect_rows","bug_5050383","plan_expression_slave",
        'recyclebin.recyclebin_sync_ddl', 'recyclebin.recyclebin_information_schema','complex_obgene_sql_1',
        'partition_part_id',
        'insert.insert_ignore_multi_stmt', 'insert.insert_ignore_one_row', 'insert.insert_ignore_one_stmt_multi_row', 'insert.insert_select_ignore', 'outline.outline_use',
        'part_mg.alter_tablegroup_timeout1'
        ] + excludes + ps_test

cp_list=['ps_affect_rows',
        'affect_rows',
        'master_ups_lost_causedby_switch_twice',
        'deadlock_causedby_ups_switch',
        'jdbc_ps_complex',
        'jdbc_trx_with_merge',
        'jdbc_parallel_trx',
        'jdbc_ps_insert',
        'jdbc_ps_all_statement',
        'hex_ip_java',
        'special_hook',
        'type_date.timestamp_2m',
        'set',
        'kill',
        'killquery',
  'decode_ps_return_type',
  'decode_return_type',
	'jdbc_replace_ps',
	'jdbc_replace_ps_trx',
	'jdbc_replace_parallel_trx',
        'insert_fail',
        'sql_audit',
        'decode_ps_return_type',
        'decode_return_type',
        'ps_lose_delete','ps_lose_delete_tr','ps_lose_insert','ps_lose_insert_tr','ps_lose_muticonn','ps_lose_replace','ps_lose_replace_tr','ps_lose_select','ps_lose_select_tr','ps_lose_update','ps_lose_update_tr','ps_muticonn_stress','ps_lose_when','ps_lose_when2',
        'ps_lose_delete','ps_lose_delete_tr','ps_lose_insert','ps_lose_insert_tr','ps_lose_muticonn','ps_lose_replace','ps_lose_replace_tr','ps_lose_select','ps_lose_select_tr','ps_lose_update','ps_lose_update_tr','ps_muticonn_stress','ps_lose_when','ps_lose_when2',
        'bind_variable_stress_65535','bind_variable_stress_greater_then_65535','vector_nps',
        'join_bigid_bug206703','update_rowkey_basic','update_rowkey_bug5003370',
         'zcreate10000table',
         'zcreateindex1000',
         'decode_extra_jdbc','func_sign','zaddlmajor_gt64times_expire_trx','zaddlmajor_gt64times', "plan_expression_slave",'optimizer.optimizer_bug_misc','sql_alloc_count','tenant.monitor', 'query_rowkey_range', 'query_eliminate_sort', 'query_with_precast', 'recyclebin.recyclebin_sync_ddl', 'recyclebin.recyclebin_information_schema',
        ] + excludes

j_list=['ps_1',
        'ps_3',
        'select_error',
        'autocommit',
	'tc_multicolumn_different',
        'hex_ip',
        'empty_input',
        'master_ups_lost_causedby_switch_twice',
        'deadlock_causedby_ups_switch',
        'delete_bug206717',
        'delete_bug206717_yzf',
	'deprecated_features',
        'information_schema.information_schema2',
        'information_schema.information_schema_db',
        'update.update_ignore_multi_stmt',
        'insert.insert_ignore_multi_stmt',
	'synchronization',
        'set',
	'create_frommysql',
	'ix_drop_error',
	'ix_drop',
	'number.ix_index_decimals',
	'ix_index_non_string',
	'ix_index_string_length',
	'ix_index_string',
	'number.ix_unique_decimals',
	'ix_unique_non_string',
	'ix_unique_string_length',
	'ix_unique_string',
	'ix_using_order',
  'serialize_6k_bug',
        'kill',
        'killquery',
        'trx_timeout',
        'create_user',
        'sql_audit',
        'create2',
        'scan_2M_size',
        'user_privilege',
        'user_pwd',
        'revoke',
        'session_timeout',
	'privileges',
	'jdbc_ps_all_statement',
        'query_method',
        'query_timeout',
	'sfu',
	'sfu2',
        'when_parallel1',
        'when_parallel3',
        'update_delete_many_data',
	'when_parallel2',
        'when_trx2',
        'join_bigid_bug206703',
        'a_trade_schema',
        'create10000table',
        'nop',
        'nop_multi_rowkey',
        'many_number_pk',
        'many_number_pk_decimal',
        'many_number_pk_large_than_58',
        'many_number_pk_timestamp',
        'many_number_pk_varchar',
        'nop_index',
        'nop_index_multi_rowkey',
        'nop_index_default',
        'java',
        'expire_trx',
        'insert_fail',
        'ps_muticonn_stress',
        'decode_ps',
        'expire_trx2',
        'trans_monitor',
        'concurrent_tablet_insert_delete',
        'type_date.timestamp_2m',
		'decode_extra',
    'zaddlmajor_gt64times',
    'zaddlmajor_gt64times_expire_trx',
    'sql_audit_c_ps',
    'transformer.impl',
    'information_schema.information_schema2',
    'information_schema.information_schema_db',
    'information_schema.information_schema_chmod',
    'information_schema.information_schema_inno',
    'plan_cache.plan_cache_update',
    'zcreate10000table',
    'zcreateindex1000',
    'create_not_windows',
	'partition.ob_partition_max_num',
	'partition.ob_partition_max_num_pk',
	'partition.partition_auto_increment_innodb',
	'view.innodb_func_view',
	'view.innodb_views',
	'information_schema.information_schema2_nt',
	'information_schema.information_schema_db_nt',
        'group_min_max',
        'show_check',
        'lowercase_table4',
        'parser_precedence_1',
        'parser',
        'mysql_comments',
        'dml_enable_info',
        'replace_and_insert_on_dup.replace_into_affected_rows',
        'replace_and_insert_on_dup.replace_with_auto_increment',
        'replace_and_insert_on_dup.replace_with_different_data_type',
        'replace_and_insert_on_dup.insert_on_duplicate_key_muti_unique_index',
        'replace_and_insert_on_dup.insert_on_duplicate_key_only_primary_key',
        'replace_and_insert_on_dup.replace_read_laster',
        'meta_info.meta_const',
        "plan_expression_slave",
        'insert_rows_sum_of_2M_size','optimizer.optimizer_bug_misc','sql_alloc_count',
        'outline.outline_basic',
        'outline.outline_concurrent',
        'query_rowkey_range', 'query_eliminate_sort', 'query_with_precast',
        'outline.create_charge_outline',
		'meta_cast', 'recyclebin.recyclebin_sync_ddl', 'recyclebin.recyclebin_information_schema',
        ] + excludes


jp_list=['meta_info.meta_build_in_func_test','meta_info.meta_func_ceil','meta_info.meta_func_floor',
    'meta_info.meta_func_gconcat','meta_info.meta_func_group_1','meta_info.meta_func_length',
    'meta_info.meta_test_func_return_type','meta_info.meta_timefuncnull','meta_info.meta_const',
    'meta_info.meta_type','meta_info.meta_func','meta_cast',
    'dml_enable_info','insert.insert2','executor_scan_2_mode',
    'dml_enable_info','insert.insert2','executor_scan_2_mode','expr_precision_scale_length',
    'update.update_ignore_multi_stmt',
    'insert.insert_ignore_multi_stmt',
    'replace_and_insert_on_dup.replace_into_affected_rows',
        'replace_and_insert_on_dup.replace_with_auto_increment',
        'replace_and_insert_on_dup.replace_with_different_data_type',
        'replace_and_insert_on_dup.insert_on_duplicate_key_muti_unique_index',
        'replace_and_insert_on_dup.insert_on_duplicate_key_only_primary_key',
        'replace_and_insert_on_dup.replace_read_laster',
    'ps_1',
        'create_not_windows',
	'crash_manytables_string',
        'tenant.resource_pool_new',
        'partition.ob_partition_max_num',
	'partition.ob_partition_max_num_pk',
	'partition.partition_auto_increment_innodb',
	'view.innodb_func_view',
	'view.innodb_views',
	'information_schema.information_schema2_nt',
	'information_schema.information_schema_db_nt',
        'ps_3',
        'select_error',
	'crash_manytables_number',
	'alter.ta_drop_string_index',
        'autocommit',
	'crash_manycolumns_number',
	'crash_manycolumns_string',
        'empty_input',
	'tc_multicolumn_different',
        'master_ups_lost_causedby_switch_twice',
        'deadlock_causedby_ups_switch',
        'delete_bug206717',
        'delete_bug206717_yzf',
        'many_columns',
        'serialize_6k_bug',
        'kill',
	'create_frommysql',
        'hex_ip',
        'killquery',
        'trx_timeout',
        'create_user',
	'deprecated_features',
        'information_schema.information_schema2',
        'information_schema.information_schema_db',
        'synchronization',
        'group_min_max',
        'show_check',
        'ix_drop_error',
        'ix_drop',
        'number.ix_index_decimals',
        'ix_index_non_string',
        'ix_index_string_length',
        'ix_index_string',
        'number.ix_unique_decimals',
        'ix_unique_non_string',
        'ix_unique_string_length',
        'ix_unique_string',
        'ix_using_order',
        'create2',
        'scan_2M_size',
        'user_privilege',
        'user_pwd',
        'revoke',
        'session_timeout',
        'many_number_pk',
        'many_number_pk_decimal',
        'many_number_pk_large_than_58',
        'many_number_pk_timestamp',
        'many_number_pk_varchar',
        'type_date.timestamp_2m',
        'decode_ps',
	      'privileges',
        'query_method',
        'query_timeout',
        'expire_trx',
        'sql_audit',
        'sql_audit_c_ps',
	'sfu',
	'sfu2',
        'when_parallel1',
        'when_parallel3',
	'when_parallel2',
	'when_trx2',
        'vector_nps',
        'a_trade_schema',
        'parallel_create_table',
        'create10000table',
        'nop',
        'nop_multi_rowkey',
        'nop_index',
        'nop_index_multi_rowkey',
        'nop_index_default',
        'java',
        'set',
        'update_delete_many_data',
        'join_bigid_bug206703',
        'ps_muticonn_stress',
        'insert_fail',
        'trans_monitor',
        'concurrent_tablet_insert_delete',
        'zcreate10000table',
        'zcreateindex1000',
		'decode_extra',
		'expire_trx2',
    'expire_trx_nop',
    'zaddlmajor_gt64times_expire_trx',
    'plan_cache.plan_cache_update',
    'zcreate10000table',
    'zcreateindex1000',
    'innodb.innodb_misc1',
    'innodb.innodb_mysql',
    'innodb.innodb',
    'execution_constants',
    'inner_table.inner_table_overall',
    'greedy_search',
    'plan_base_line_for_schema',
        'comment_stmt',
        'parser_precedence_1',
        'parser',
        'mysql_comments',
        'lowercase_table4',
        'func_in_none',
        'derived',
        'trx.init_innodb',
        'trx.rr_id_3',
        'trx.rr_sc_sum_total',
        'trx.rr_u_4',
        'trx.deadlock',
        'consistent_snapshot',
        "plan_expression_slave",
        "show_create",
        'insert_rows_sum_of_2M_size',
        'optimizer.optimizer_bug_misc',
        'sql_alloc_count',
        'outline.outline_basic',
        'outline.outline_concurrent',
         'union1',
         'outline.create_charge_outline', 'recyclebin.recyclebin_sync_ddl', 'recyclebin.recyclebin_information_schema'
        ] + excludes

o_list=['ps_affect_rows',
        'affect_rows',
        'master_ups_lost_causedby_switch_twice',
        'deadlock_causedby_ups_switch',
        'jdbc_ps_complex',
        'jdbc_trx_with_merge',
        'jdbc_parallel_trx',
        'jdbc_ps_insert',
        'create_use',
        'revoke',
        'user_privilege',
        'rename_user',
        'kill',
        'killquery',
	'set',
	'jdbc_replace_ps',
	'jdbc_replace_ps_trx',
	'jdbc_replace_parallel_trx',
        'create_user',
        'trx_timeout',
        'session_timeout',
        'ps_lose_delete','ps_lose_delete_tr','ps_lose_insert','ps_lose_insert_tr','ps_lose_muticonn','ps_lose_replace','ps_lose_replace_tr','ps_lose_select','ps_lose_select_tr','ps_lose_update','ps_lose_update_tr','ps_muticonn_stress','jdbc_ps_all_statement','ps_lose_when','ps_lose_when2',
        'query_method',
        'lowercase_table4',
        "plan_expression_slave",
        'optimizer.optimizer_bug_misc','sql_alloc_count','tenant.monitor',
        'query_rowkey_range', 'query_eliminate_sort', 'query_with_precast'
        ] + excludes

op_list=['ps_affect_rows',
        'affect_rows',
        'master_ups_lost_causedby_switch_twice',
        'deadlock_causedby_ups_switch',
        'jdbc_ps_complex',
        'jdbc_trx_with_merge',
        'jdbc_parallel_trx',
        'jdbc_ps_insert',
        'build_in_func_test',
        'create_user',
        'revoke',
        'user_privilege',
        'rename_user',
        'kill',
        'killquery',
	'set',
	'jdbc_replace_parallel_trx',
        'create_user',
	'jdbc_replace_ps',
	'jdbc_replace_ps_trx',
        'trx_timeout',
        'session_timeout',
        'query_method',
        'ps_lose_delete','ps_lose_delete_tr','ps_lose_insert','ps_lose_insert_tr','ps_lose_muticonn','ps_lose_replace','ps_lose_replace_tr','ps_lose_select','ps_lose_select_tr','ps_lose_update','ps_lose_update_tr','ps_muticonn_stress','jdbc_ps_all_statement','ps_lose_when','ps_lose_when2','vector_nps',
        "plan_expression_slave",
        'optimizer.optimizer_bug_misc','sql_alloc_count', 'tenant.monitor',
        'query_rowkey_range', 'query_eliminate_sort', 'query_with_precast'
        ] + excludes

remote_list=['plan_base_line',
             'plan_base_line_for_schema',
             'zcreate10000table',
             'zcreateindex1000',
             'kill',
             'innodb_icp',
             'optimizer.optimizer_bug_misc',
             'only_full_group_by_sql_mode',
             'sql_alloc_count',
             'project_pruning',
             'index_orderby_select_unique_idx',
             'aggregate_rewrite',
             'late_materialization',
             'kill_transaction',
             'partition.partition_range',
             'cbo',
             'partition.ob_partition_location',
             'select_distinct',
             'delete_alias',
             'generated_column_basic',
             'generated_column',
             'time_zone.time_zone_usage',
             'join.anti_semi_join',
            ] + excludes

slave_list=['scan_2M_size','update_delete_many_data','insert_rows_sum_of_2M_size','information_schema',
    'join_bigid_bug206703','tenant2', 'tenant3','simple_ddl','join.join_outer_new','show',
    'plan_cache.plan_cache_update','information_schema.information_schema_desc',
    'information_schema.information_schema_select','group_min_max','aggregate_rewrite','order_by',
    'show_check', 'innodb.innodb', 'innodb.innodb_mysql', 'negation_elimination','subselect_innodb',
    'limit_update_delete',
    'greedy_search','greedy_optimizer','case','write_timeout','dml_update_multi_partition',
    'write_timeout', 'innodb.innodb_pk_extension_on',
    'information_schema.information_schema2','information_schema.information_schema-big','tenant',
    'derived', 'func_in_none', 'group_by1','union1',
    'group_by_1', 'eq_range_idx_stat','join.join_blk_nested', 'partition.partition_locking','optimizer.optimizer_bug_misc', 'only_full_group_by_sql_mode',
    'inner_table.tenant_virtual_outline', 'tenant.create_many_tiny','inner_table.tenant_virtual_concurrent_limit_sql',
    'query_rowkey_range', 'query_eliminate_sort', 'query_with_precast',
    'inner_table.all_virtual_sql_plan_monitor', 'test_partition_id', 'bit_type.bit_column_dml', 'recyclebin.recyclebin_sync_ddl', 'recyclebin.recyclebin_information_schema',
    'transformer.or_expansion','acs.acs_basic','plan_cache_elimination_for_buffer_table', 'found_rows_show_stmt',
    'partition_part_id',
    'spm.spm_new_plan_not_ok', 'spm.spm_new_plan_ok', 'so_udf', 'spm.spm_repeated_add_baseline',
    'insert.insert_ignore_multi_stmt', 'insert.insert_ignore_one_row', 'insert.insert_ignore_one_stmt_multi_row', 'insert.insert_select_ignore', 'plan_cache.plan_cache_same_name',
    'outline.outline_use', "spm.spm_banned_plan", "spm.spm_fixed_baseline",
    'part_mg.alter_tablegroup_timeout1', 'replace_multi_partition', 'spm.spm_param_info', 'plan_cache.plan_cache_insert_uncertain_op'
           ]+remote_list+c_list+excludes
proxy_list=['inner_table.all_virtual_sql_plan_monitor', 'scan_2M_size','join_bigid_bug206703','join.join_outer_new', "plan_expression_slave","eq_range_idx_stat","greedy_search","synchronization",'join.join_blk_nested','greedy_optimizer', 'derived','optimizer.optimizer_bug_misc', 'plan_cache.plan_cache_update', 'plan_cache.plan_cache_memory', 'plan_cache.plan_cache_outline', 'only_full_group_by_sql_mode','sql_alloc_count', 'sys_vars.init_connect_var', 'outline.outline_basic', 'query_rowkey_range', 'query_eliminate_sort', 'query_with_precast', 'sys_vars.init_connect_var'
           ]+remote_list+c_list+excludes


