{
 "title": "SeekDB Metrics",
 "description": "seekdb metrics collected from seekdb using obagent",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "app", "query": { "query": "label_values(app)" } },
   {
    "name": "svr_ip",
    "query": {
     "query": "label_values({app=~\"$app\"}, svr_ip)"
    }
   },
   {
    "name": "svr_port",
    "query": {
     "query": "label_values({app=~\"$app\",svr_ip=~\"$svr_ip\"}, svr_port)"
    }
   },
   { "name": "group", "query": "svr_ip, svr_port" }
  ]
 },
 "panels": [
  { "title": "SQL and Session", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(seekdb_sysstat{stat_id=\"40002\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) + sum(rate(seekdb_sysstat{stat_id=\"40004\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) + sum(rate(seekdb_sysstat{stat_id=\"40006\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) + sum(rate(seekdb_sysstat{stat_id=\"40008\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) + sum(rate(seekdb_sysstat{stat_id=\"40000\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "qps {{$group}}"
    }
   ]
  },
  {
   "title": "Sql Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "(sum(rate(seekdb_sysstat{stat_id=\"40003\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) + sum(rate(seekdb_sysstat{stat_id=\"40005\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) + sum(rate(seekdb_sysstat{stat_id=\"40007\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) + sum(rate(seekdb_sysstat{stat_id=\"40009\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) + sum(rate(seekdb_sysstat{stat_id=\"40001\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group))\n/\n(sum(rate(seekdb_sysstat{stat_id=\"40002\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) + sum(rate(seekdb_sysstat{stat_id=\"40004\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) + sum(rate(seekdb_sysstat{stat_id=\"40006\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) + sum(rate(seekdb_sysstat{stat_id=\"40008\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) + sum(rate(seekdb_sysstat{stat_id=\"40000\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group))",
     "legendFormat": "sql latency {{$group}}"
    }
   ]
  },
  {
   "title": "SQL plan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(seekdb_sysstat{stat_id=\"40012\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "distributed {{ $group }}"
    },
    {
     "expr": "sum(rate(seekdb_sysstat{stat_id=\"40010\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "local {{ $group }}"
    },
    {
     "expr": "sum(rate(seekdb_sysstat{stat_id=\"40011\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "remote {{$group}}"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(seekdb_active_session_num{app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}) by ($group)",
     "legendFormat": "sessions {{ $group }}"
    }
   ]
  },
  { "title": "Transaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(seekdb_sysstat{stat_id=\"30005\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "tps {{$group}}"
    }
   ]
  },
  {
   "title": "Transaction Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(rate(seekdb_sysstat{stat_id=\"30006\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) / sum(rate(seekdb_sysstat{stat_id=\"30005\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "trans rt {{$group}}"
    }
   ]
  },
  {
   "title": "Transaction Log",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(seekdb_sysstat{stat_id=\"30002\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "trans log {{$group}}"
    }
   ]
  },
  {
   "title": "Trans Log Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(seekdb_sysstat{stat_id=\"80057\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "trans log {{$group}}"
    }
   ]
  },
  {
   "title": "Transaction Log Sync Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(rate(seekdb_sysstat{stat_id=\"30000\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) / sum(rate(seekdb_sysstat{stat_id=\"30001\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "sync latency {{ $group }}"
    }
   ]
  },
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Cpu Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(seekdb_sysstat{stat_id=\"140006\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}) by ($group) / sum(seekdb_sysstat{stat_id=\"140005\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}) by ($group)",
     "legendFormat": "cpu util {{$group}}"
    }
   ]
  },
  {
   "title": "Memstore Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(seekdb_sysstat{stat_id=\"130001\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}) by ($group) / sum(seekdb_sysstat{stat_id=\"130004\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}) by ($group)",
     "legendFormat": "memstore percent {{$group}}"
    }
   ]
  },
  {
   "title": "Memstore Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(seekdb_sysstat{stat_id=\"130004\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}) by ($group)",
     "legendFormat": "limit {{$group}}"
    },
    {
     "expr": "sum(seekdb_sysstat{stat_id=\"130001\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}) by ($group)",
     "legendFormat": "total {{$group}}"
    },
    {
     "expr": "sum(seekdb_sysstat{stat_id=\"130000\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}) by ($group)",
     "legendFormat": "active {{$group}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(seekdb_sysstat{stat_id=\"60000\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "read {{$group}}"
    },
    {
     "expr": "sum(rate(seekdb_sysstat{stat_id=\"60003\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "write {{$group}}"
    }
   ]
  },
  {
   "title": "IO Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(seekdb_sysstat{stat_id=\"60002\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "read {{$group}}"
    },
    {
     "expr": "sum(rate(seekdb_sysstat{stat_id=\"60005\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "write {{$group}}"
    }
   ]
  },
  {
   "title": "IO Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(rate(seekdb_sysstat{stat_id=\"60001\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) / sum(rate(seekdb_sysstat{stat_id=\"60000\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "read {{$group}}"
    },
    {
     "expr": "sum(rate(seekdb_sysstat{stat_id=\"60004\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) / sum(rate(seekdb_sysstat{stat_id=\"60003\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "write {{$group}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(seekdb_cache_size_bytes{cache_name=\"user_row_cache\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}) by ($group)",
     "legendFormat": "row_cache {{$group}}"
    },
    {
     "expr": "sum(seekdb_cache_size_bytes{cache_name=\"user_block_cache\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}) by ($group)",
     "legendFormat": "block_cache {{$group}}"
    },
    {
     "expr": "sum(seekdb_plan_cache_memory_bytes{app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}) by ($group)",
     "legendFormat": "plan_cache {{$group}}"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 / (1 + sum(rate(seekdb_sysstat{stat_id=\"50001\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) / sum(rate(seekdb_sysstat{stat_id=\"50000\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group))",
     "legendFormat": "row_cache {{$group}}"
    },
    {
     "expr": " 1 / (1 + sum(rate(seekdb_sysstat{stat_id=\"50009\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) / sum(rate(seekdb_sysstat{stat_id=\"50008\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group))",
     "legendFormat": "block_cache {{$group}}"
    },
    {
     "expr": "sum(rate(seekdb_plan_cache_hit_total{app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) / sum(rate(seekdb_plan_cache_access_total{app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "plan_cache {{$group}}"
    }
   ]
  },
  { "title": "Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Queue",
   "type": "timeseries",
   "description": "request dequeue count",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(seekdb_sysstat{stat_id=\"20001\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "queue {{ $group }}"
    }
   ]
  },
  {
   "title": "Queue Time",
   "type": "timeseries",
   "description": "request queue time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(rate(seekdb_sysstat{stat_id=\"20002\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) / sum(rate(seekdb_sysstat{stat_id=\"20001\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "queue time {{ $group }}"
    }
   ]
  },
  { "title": "Lock", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Lock Wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(seekdb_sysstat{stat_id=\"60021\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "succ {{$group}}"
    },
    {
     "expr": "sum(rate(seekdb_sysstat{stat_id=\"60022\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "fail {{$group}}"
    }
   ]
  },
  {
   "title": "Lock Wait Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(rate(seekdb_sysstat{stat_id=\"60023\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) / (sum(rate(seekdb_sysstat{stat_id=\"60021\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) + sum(rate(seekdb_sysstat{stat_id=\"60022\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group))",
     "legendFormat": "wait_time {{$group}}"
    }
   ]
  },
  { "title": "Rpc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Rpc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(seekdb_sysstat{stat_id=\"10001\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "rpc in {{$group}}"
    },
    {
     "expr": "sum(rate(seekdb_sysstat{stat_id=\"10003\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "rpc_out {{$group}}"
    }
   ]
  },
  {
   "title": "Rpc Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(seekdb_sysstat{stat_id=\"10005\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) + sum(rate(seekdb_sysstat{stat_id=\"10006\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)) / sum(rate(seekdb_sysstat{stat_id=\"10000\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "rpc in Latency {{$group}}"
    },
    {
     "expr": "(sum(rate(seekdb_sysstat{stat_id=\"10005\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) + sum(rate(seekdb_sysstat{stat_id=\"10006\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)) / sum(rate(seekdb_sysstat{stat_id=\"10002\",app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "rpc out latency {{$group}}"
    }
   ]
  },
  { "title": "Wait Event", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Wait Event",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(seekdb_waitevent_wait_total{app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "wait event {{$group}}"
    }
   ]
  },
  {
   "title": "Wait Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(seekdb_waitevent_wait_seconds_total{app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group) / sum(rate(seekdb_waitevent_wait_total{app=~\"$app\",svr_ip=~\"$svr_ip\",svr_port=~\"$svr_port\"}[$__rate_interval])) by ($group)",
     "legendFormat": "wait time {{$group}}"
    }
   ]
  }
 ]
}